-- MySQL Script generated by MySQL Workbench
-- Wed Apr 29 22:25:28 2020
-- Model: Votemyst    Version: 1.0
-- MySQL Workbench Forward Engineeringuserdata

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema votemyst
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema votemyst
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `votemyst` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema votemyst
-- -----------------------------------------------------
USE `votemyst` ;

-- -----------------------------------------------------
-- Table `votemyst`.`userdata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votemyst`.`userdata` (
  `snowflake` BIGINT NOT NULL,
  `first_seen` DATETIME NULL,
  PRIMARY KEY (`snowflake`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `votemyst`.`votes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votemyst`.`votes` (
  `vote_id` INT NOT NULL AUTO_INCREMENT,
  `snowflake` BIGINT NOT NULL,
  `entry_id` INT NOT NULL,
  `vote_date` DATETIME NOT NULL,
  PRIMARY KEY (`vote_id`, `snowflake`, `entry_id`),
  UNIQUE INDEX `vote_id_UNIQUE` (`vote_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `votemyst`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votemyst`.`events` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `vote_end_date` DATETIME NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `description` VARCHAR(512) NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `event_id_UNIQUE` (`event_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `votemyst`.`entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `votemyst`.`entries` (
  `entry_id` INT NOT NULL AUTO_INCREMENT,
  `event_id` INT NOT NULL,
  `snowflake` BIGINT NOT NULL,
  `entry_date` DATETIME NOT NULL,
  `entry_type` INT NOT NULL,
  `entry` VARCHAR(512) NOT NULL,
  PRIMARY KEY (`entry_id`, `event_id`, `snowflake`),
  UNIQUE INDEX `entry_id_UNIQUE` (`entry_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
